-- Staging Table for Contract Input History Mockup

[Staging].[CVC_Contracts](
[PK] [int] IDENTITY(1,1) NOT NULL,
[CVC_Contracts_PK] [int] NOT NULL,
[Contract_No] [varchar](3) NOT NULL,
[JobNo] [varchar](6) NULL,
[Contract_Description] [varchar](20) NULL,
[Contract_Date] [varchar](10) NULL,
[Builder_Eff_Release] [varchar](3) NULL,
[Eff Date] [varchar](10) NULL,
[Estimate_PK] [int] NOT NULL,
--[Lookup] [int] NOT NULL, GREG PLEASE FIX THIS ONE
[Plan_Name] [varchar](20) NULL,
[ELV_OPT] [varchar](20) NULL,
[Identifying_Notes] [varchar](20) NULL,
[Footprint_SF] [decimal](12, 0) NULL,
[Labor_MH] [decimal](12, 0) NULL,
[Concrete_CY] [decimal](12, 0) NULL,
[Rock_TN] [decimal](12, 0) NULL,
[Steel_LBS] [decimal](12, 0) NULL,
[PT_Cable_LF] [decimal](12, 0) NULL,
[Pumping_CY] [decimal](12, 0) NULL,
[Lumber_BF] [decimal](12, 0) NULL,
[Sage_Estimate_Amount] [decimal](12, 2) NULL,
[RFA_Amount] [decimal](12, 2) NULL,
[Proposal_Amount] [decimal](12, 2) NULL,
[Draw_1] [decimal](12, 2) NULL,
[Draw_2] [decimal](12, 2) NULL,
[Draw_3] [decimal](12, 2) NULL,
[Draw_4] [decimal](12, 2) NULL,
[OCIP_Amount] [varchar](20) NULL,
[Contract_Amount] [decimal](12, 2) NULL,
[Contract_vs_Proposal_Delta] [decimal](12, 2) NULL,
[Delta_Variance_Percent] [varchar](8) NULL,
[Created_by] [varchar](15) NULL,
[Created date] [datetime] NULL,
[Estimate_Name] [varchar](30) NULL,
[Proposal_Name] [varchar](30) NULL,
[Contract_File_Name] [varchar](30) NULL,
[Notes] [varchar](30) NULL,


